import os
from datetime import datetime
from typing import List

from models import Lead


def generate_markdown_report(leads: List[Lead], date_str: str = None) -> str:
    if date_str is None:
        date_str = datetime.now().strftime("%Y-%m-%d")

    lines = []
    lines.append(f"# Facebook Daily Lead Radar - Top 10 ({date_str})")
    lines.append("")
    lines.append(f"> 共筛选 {len(leads)} 条高质量线索（按综合评分排序）")
    lines.append("")

    yes_count = sum(1 for l in leads if l.contact_recommendation == "YES")
    maybe_count = sum(1 for l in leads if l.contact_recommendation == "MAYBE")
    no_count = sum(1 for l in leads if l.contact_recommendation == "NO")

    lines.append(f"- ✅ **YES（建议联系）**: {yes_count}")
    lines.append(f"- ⚠️ **MAYBE（可以试试）**: {maybe_count}")
    lines.append(f"- ❌ **NO（不建议）**: {no_count}")
    lines.append("")
    lines.append("---")
    lines.append("")

    for idx, lead in enumerate(leads, 1):
        lines.append(f"## {idx}. 【{lead.contact_recommendation}】评分 {lead.total_score}/10")
        lines.append("")
        lines.append(f"- **发帖人**: {lead.lead_name or '未知'}")
        lines.append(f"- **群组**: {lead.group_name or '未知'}")
        lines.append(f"- **帖子链接**: {lead.post_url or '无'}")
        lines.append(f"- **需求类型**: {_format_need_type(lead.detected_need_type)}")
        lines.append(f"- **发布时间**: {lead.post_time or '未知'}")
        lines.append("")

        lines.append(f"### 原帖摘要")
        lines.append("")
        summary = _truncate(lead.post_text, 300)
        lines.append(f"> {summary}")
        lines.append("")

        lines.append(f"### 为什么适合我")
        lines.append("")
        lines.append(lead.why_good_fit or "匹配度一般")
        lines.append("")

        lines.append(f"### 风险 / 不适合点")
        lines.append("")
        lines.append(lead.why_risk or "无明显不匹配点")
        lines.append("")

        lines.append(f"### 建议切入角度")
        lines.append("")
        lines.append(lead.suggested_angle)
        lines.append("")

        lines.append(f"### 一句人工私信用语")
        lines.append("")
        lines.append(f"```")
        lines.append(lead.suggested_manual_reply)
        lines.append(f"```")
        lines.append("")

        lines.append("---")
        lines.append("")

    lines.append("## 使用说明")
    lines.append("")
    lines.append("1. 优先联系 YES 级别的线索")
    lines.append("2. 私信时不要照搬脚本，改成你自己的语气")
    lines.append("3. 不要一上来提 USDT，先聊需求")
    lines.append("4. 把范围拉到 small first fix，不要一口吃个胖子")
    lines.append("5. 先让对方发店铺链接，看完再说能帮什么")
    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by Facebook Lead Radar on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

    return "\n".join(lines)


def save_report(leads: List[Lead], output_dir: str = "reports", date_str: str = None) -> str:
    if date_str is None:
        date_str = datetime.now().strftime("%Y-%m-%d")

    os.makedirs(output_dir, exist_ok=True)
    filename = f"daily_facebook_leads_{date_str}.md"
    filepath = os.path.join(output_dir, filename)

    content = generate_markdown_report(leads, date_str)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return filepath


def save_csv(leads: List[Lead], output_dir: str = "reports", date_str: str = None) -> str:
    import csv

    if date_str is None:
        date_str = datetime.now().strftime("%Y-%m-%d")

    os.makedirs(output_dir, exist_ok=True)
    filename = f"daily_facebook_leads_{date_str}.csv"
    filepath = os.path.join(output_dir, filename)

    fieldnames = [
        "rank", "total_score", "lead_name", "group_name", "post_url",
        "detected_need_type", "post_text_summary", "why_good_fit",
        "why_risk", "suggested_angle", "suggested_manual_reply",
        "contact_recommendation", "post_time",
    ]

    with open(filepath, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for idx, lead in enumerate(leads, 1):
            writer.writerow({
                "rank": idx,
                "total_score": lead.total_score,
                "lead_name": lead.lead_name,
                "group_name": lead.group_name,
                "post_url": lead.post_url,
                "detected_need_type": lead.detected_need_type,
                "post_text_summary": _truncate(lead.post_text, 200),
                "why_good_fit": lead.why_good_fit,
                "why_risk": lead.why_risk,
                "suggested_angle": lead.suggested_angle,
                "suggested_manual_reply": lead.suggested_manual_reply,
                "contact_recommendation": lead.contact_recommendation,
                "post_time": lead.post_time,
            })

    return filepath


def _format_need_type(need_type: str) -> str:
    mapping = {
        "store_review": "店铺求点评",
        "no_sales": "有流量没转化",
        "building_phase": "店铺建设中",
        "shopify_designer_needed": "找 Shopify 设计师",
        "product_page_help": "产品页需要帮助",
        "product_visuals_needed": "需要产品视觉素材",
        "promo_video_needed": "需要推广短视频",
        "digital_product_store": "数字产品店",
        "handmade_or_craft_store": "手工/手作店",
        "unclear_or_low_quality": "需求不明确/低质量",
    }
    return mapping.get(need_type, need_type)


def _truncate(text: str, max_len: int) -> str:
    text = text.strip()
    if len(text) <= max_len:
        return text
    return text[:max_len] + "..."
